"use client";
import { FormEvent, useState } from "react";

type EventItem = { id:string; title:string; slug:string; status:string; position:number; photoCount:number };
export function Studio({ initialEvents, signOutPath }: { initialEvents:EventItem[]; signOutPath:string }) {
  const [events,setEvents]=useState(initialEvents); const [busy,setBusy]=useState(false); const [message,setMessage]=useState("");
  async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const form=new FormData(e.currentTarget);const r=await fetch("/api/studio/events",{method:"POST",body:form});const data=await r.json();if(r.ok){setEvents([...events,data.event]);e.currentTarget.reset();setMessage("Draft created.")}else setMessage(data.error);setBusy(false)}
  async function update(id:string,action:"publish"|"draft"|"delete") { setBusy(true); const r=await fetch(`/api/studio/events/${id}`,{method:action==="delete"?"DELETE":"PATCH",headers:{"content-type":"application/json"},body:action==="delete"?undefined:JSON.stringify({status:action==="publish"?"published":"draft"})}); if(r.ok){setEvents(action==="delete"?events.filter(x=>x.id!==id):events.map(x=>x.id===id?{...x,status:action==="publish"?"published":"draft"}:x));setMessage(action==="delete"?"Event deleted.":action==="publish"?"Published.":"Moved to draft.")} setBusy(false) }
  async function upload(id:string,files:FileList|null){if(!files?.length)return;setBusy(true);setMessage("Preparing photos…");const form=new FormData();for(const file of Array.from(files)){try{form.append("photos",await preparePhoto(file),file.name.replace(/\.[^.]+$/,"")+".webp")}catch{setMessage(`${file.name} could not be prepared.`)}}const r=await fetch(`/api/studio/events/${id}/photos`,{method:"POST",body:form});const data=await r.json();if(r.ok){setEvents(events.map(x=>x.id===id?{...x,photoCount:x.photoCount+data.count}:x));setMessage(`${data.count} photo${data.count===1?"":"s"} added.`)}else setMessage(data.error);setBusy(false)}
  return <main className="studio-shell">
    <header className="studio-header"><div><p>Private studio</p><h1>Clark Lo</h1></div><div><a href="/">View site ↗</a><a href={signOutPath}>Sign out</a></div></header>
    <section className="studio-new"><h2>New event</h2><form onSubmit={create}><label>Event title<input name="title" required placeholder="e.g. Sports Day" /></label><button className="studio-button" disabled={busy}>Create draft <span>↗</span></button></form></section>
    <section className="studio-events"><div className="studio-section-title"><h2>Events</h2><span>{events.length}</span></div>{events.length?events.map((item,index)=><article className="studio-event" key={item.id}><span className="studio-index">{String(index+1).padStart(2,"0")}</span><div className="studio-event-name"><h3>{item.title}</h3><p>{item.photoCount} photos · {item.status}</p></div><label className="studio-upload">Add photos<input type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={e=>upload(item.id,e.target.files)} /></label><button onClick={()=>update(item.id,item.status==="published"?"draft":"publish")} disabled={busy}>{item.status==="published"?"Unpublish":"Publish"}</button><button className="studio-delete" onClick={()=>update(item.id,"delete")} disabled={busy}>Delete</button></article>):<p className="studio-empty">Create your first event, then add the photographs you want to share.</p>}</section>
    <p className="studio-status" role="status">{message}</p>
  </main>
}

async function preparePhoto(file:File):Promise<Blob>{const bitmap=await createImageBitmap(file);const max=2400,scale=Math.min(1,max/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement("canvas");canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);const context=canvas.getContext("2d");if(!context)throw new Error("Canvas unavailable");context.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();return new Promise((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error("Conversion failed")),"image/webp",.88))}
